// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTHDIAv_Wid-QOQa_6y1vwsKm5auSiuMU',
    appId: '1:93353018228:web:7b88130af5ab8a12f66221',
    messagingSenderId: '93353018228',
    projectId: 'payflow-5f350',
    authDomain: 'payflow-5f350.firebaseapp.com',
    storageBucket: 'payflow-5f350.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApWhDirRK0xZYm-QQ_OUXTNqDSbOa8iEc',
    appId: '1:93353018228:android:14bef0e97abe5f8af66221',
    messagingSenderId: '93353018228',
    projectId: 'payflow-5f350',
    storageBucket: 'payflow-5f350.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcwLi_T_-fCyq9CJ_CI2y0HQuuBVHmaIo',
    appId: '1:93353018228:ios:76dd5f486456d4b6f66221',
    messagingSenderId: '93353018228',
    projectId: 'payflow-5f350',
    storageBucket: 'payflow-5f350.appspot.com',
    androidClientId: '93353018228-djptjk5717doqqcp0ii680usthf9ftsu.apps.googleusercontent.com',
    iosClientId: '93353018228-tdr24rfiu45u6r91iepqfti0l5prft00.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcwLi_T_-fCyq9CJ_CI2y0HQuuBVHmaIo',
    appId: '1:93353018228:ios:76dd5f486456d4b6f66221',
    messagingSenderId: '93353018228',
    projectId: 'payflow-5f350',
    storageBucket: 'payflow-5f350.appspot.com',
    androidClientId: '93353018228-djptjk5717doqqcp0ii680usthf9ftsu.apps.googleusercontent.com',
    iosClientId: '93353018228-tdr24rfiu45u6r91iepqfti0l5prft00.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
